server:
  port: 8068
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hk1997
mybatis:
  type-aliases-package: com.answer.base.entity
  mapper-locations: classpath:mappers/*.xml