server:
  port: 8068
spring:
  datasource:
    url: jdbc:mysql://47.110.65.233:3306/base?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ig!zY8wgsiqla
mybatis:
  type-aliases-package: com.answer.base.entity
  mapper-locations: classpath:mappers/*.xml