server:
  port: 8068
  projectName: 【陈湖旧事】
wx:
  appid: wx50c794bc3a1857fe  #微信小程序 appid
  appsecret: e735720006791179fe186a160c194553 # 微信小程序 appsecret
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={0}&secret={1}
  token: chenlaketoken
  appid2: wx60232a5b2a81142e  #微信公众号的 appid
  appsecret2: c547487c5169f4a564a4f14e12b83f5d #微信公众号的 appsecret

token:
  security:
    jwt-key: 418052
    token-expired-in: 8640
    default-scope: 8


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.65.233:3306/base?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: base
    password: cheGDWFGy4f5hJmY
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 516994147@qq.com #发送邮件的邮箱地址
    password:  jcuffvkltyxfbjce #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 516994147@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8


mybatis:
  type-aliases-package: com.answer.base.entity
  mapper-locations: classpath:mappers/*.xml

pagehelper:
  helper-dialect: mysql

upload:
  path: /www/server/tomcat
